<?php
/**
 * Installation Script for ModernShop E-Commerce
 * Run this script once to set up the application
 */

// Check if already installed
if (file_exists('config/installed.lock')) {
    die('Application is already installed. Delete config/installed.lock to reinstall.');
}

// Check PHP version
if (version_compare(PHP_VERSION, '7.4.0', '<')) {
    die('PHP 7.4 or higher is required. Current version: ' . PHP_VERSION);
}

// Check required extensions
$required_extensions = ['pdo', 'pdo_mysql', 'mbstring', 'openssl', 'json'];
$missing_extensions = [];

foreach ($required_extensions as $ext) {
    if (!extension_loaded($ext)) {
        $missing_extensions[] = $ext;
    }
}

if (!empty($missing_extensions)) {
    die('Missing required PHP extensions: ' . implode(', ', $missing_extensions));
}

// Handle form submission
if ($_POST) {
    $db_host = $_POST['db_host'] ?? 'localhost';
    $db_name = $_POST['db_name'] ?? 'ecommerce_db';
    $db_user = $_POST['db_user'] ?? '';
    $db_pass = $_POST['db_pass'] ?? '';
    $app_url = rtrim($_POST['app_url'] ?? '', '/');
    $admin_email = $_POST['admin_email'] ?? '';
    $admin_password = $_POST['admin_password'] ?? '';
    
    $errors = [];
    
    // Validate inputs
    if (empty($db_user)) $errors[] = 'Database username is required';
    if (empty($app_url)) $errors[] = 'Application URL is required';
    if (empty($admin_email)) $errors[] = 'Admin email is required';
    if (empty($admin_password)) $errors[] = 'Admin password is required';
    if (strlen($admin_password) < 6) $errors[] = 'Admin password must be at least 6 characters';
    
    if (empty($errors)) {
        try {
            // Test database connection
            $pdo = new PDO("mysql:host=$db_host", $db_user, $db_pass);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            
            // Create database if it doesn't exist
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo->exec("USE `$db_name`");
            
            // Read and execute schema
            $schema = file_get_contents('database/schema.sql');
            $pdo->exec($schema);
            
            // Update admin user with provided credentials
            $hashed_password = password_hash($admin_password, PASSWORD_DEFAULT);
            $stmt = $pdo->prepare("UPDATE users SET email = ?, password = ? WHERE role = 'admin' LIMIT 1");
            $stmt->execute([$admin_email, $hashed_password]);
            
            // Create config file
            $config_content = "<?php
/**
 * Application Configuration
 * Generated by installation script
 */

// Database Configuration
define('DB_HOST', '$db_host');
define('DB_NAME', '$db_name');
define('DB_USER', '$db_user');
define('DB_PASS', '$db_pass');

// Application Configuration
define('APP_NAME', 'ModernShop');
define('APP_URL', '$app_url');
define('APP_ENV', 'production');
define('APP_DEBUG', false);

// Security
define('HASH_ALGO', PASSWORD_DEFAULT);
define('SESSION_LIFETIME', 3600); // 1 hour

// Pagination
define('PRODUCTS_PER_PAGE', 12);
define('ORDERS_PER_PAGE', 10);

// File Upload
define('UPLOAD_PATH', __DIR__ . '/../public/uploads/');
define('MAX_FILE_SIZE', 5 * 1024 * 1024); // 5MB

// Email Configuration (configure as needed)
define('MAIL_HOST', 'localhost');
define('MAIL_PORT', 587);
define('MAIL_USERNAME', '');
define('MAIL_PASSWORD', '');
define('MAIL_FROM_EMAIL', '$admin_email');
define('MAIL_FROM_NAME', 'ModernShop');

// Timezone
date_default_timezone_set('UTC');

// Error Reporting
if (APP_DEBUG) {
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
} else {
    error_reporting(0);
    ini_set('display_errors', 0);
}
";
            
            file_put_contents('config/config.php', $config_content);
            
            // Create directories
            $directories = [
                'public/uploads/products',
                'public/uploads/categories',
                'public/uploads/users'
            ];
            
            foreach ($directories as $dir) {
                if (!is_dir($dir)) {
                    mkdir($dir, 0755, true);
                }
            }
            
            // Create installation lock file
            file_put_contents('config/installed.lock', date('Y-m-d H:i:s'));
            
            $success = true;
            
        } catch (Exception $e) {
            $errors[] = 'Database error: ' . $e->getMessage();
        }
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ModernShop Installation</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 2rem;
        }
        
        .install-container {
            background: white;
            border-radius: 12px;
            box-shadow: 0 20px 40px rgba(0,0,0,0.1);
            padding: 3rem;
            max-width: 500px;
            width: 100%;
        }
        
        .install-header {
            text-align: center;
            margin-bottom: 2rem;
        }
        
        .install-header h1 {
            color: #333;
            font-size: 2rem;
            margin-bottom: 0.5rem;
        }
        
        .install-header p {
            color: #666;
        }
        
        .form-group {
            margin-bottom: 1.5rem;
        }
        
        .form-label {
            display: block;
            margin-bottom: 0.5rem;
            font-weight: 500;
            color: #333;
        }
        
        .form-input {
            width: 100%;
            padding: 0.75rem;
            border: 2px solid #e1e5e9;
            border-radius: 6px;
            font-size: 1rem;
            transition: border-color 0.3s;
        }
        
        .form-input:focus {
            outline: none;
            border-color: #667eea;
        }
        
        .btn {
            width: 100%;
            padding: 0.875rem;
            background: #667eea;
            color: white;
            border: none;
            border-radius: 6px;
            font-size: 1rem;
            font-weight: 500;
            cursor: pointer;
            transition: background 0.3s;
        }
        
        .btn:hover {
            background: #5a6fd8;
        }
        
        .alert {
            padding: 1rem;
            border-radius: 6px;
            margin-bottom: 1.5rem;
        }
        
        .alert-error {
            background: #fee;
            color: #c53030;
            border: 1px solid #fed7d7;
        }
        
        .alert-success {
            background: #f0fff4;
            color: #2d7d32;
            border: 1px solid #c6f6d5;
        }
        
        .success-content {
            text-align: center;
        }
        
        .success-content h2 {
            color: #2d7d32;
            margin-bottom: 1rem;
        }
        
        .success-content a {
            display: inline-block;
            margin-top: 1rem;
            padding: 0.75rem 1.5rem;
            background: #667eea;
            color: white;
            text-decoration: none;
            border-radius: 6px;
            transition: background 0.3s;
        }
        
        .success-content a:hover {
            background: #5a6fd8;
        }
    </style>
</head>
<body>
    <div class="install-container">
        <?php if (isset($success) && $success): ?>
            <div class="success-content">
                <h2>Installation Complete!</h2>
                <p>ModernShop has been successfully installed and configured.</p>
                <p><strong>Admin Login:</strong><br>
                Email: <?= htmlspecialchars($admin_email) ?><br>
                Password: [as entered]</p>
                <a href="<?= htmlspecialchars($app_url) ?>">Visit Your Store</a>
                <a href="<?= htmlspecialchars($app_url) ?>/admin">Admin Panel</a>
            </div>
        <?php else: ?>
            <div class="install-header">
                <h1>ModernShop</h1>
                <p>E-Commerce Installation</p>
            </div>
            
            <?php if (!empty($errors)): ?>
                <div class="alert alert-error">
                    <?php foreach ($errors as $error): ?>
                        <div><?= htmlspecialchars($error) ?></div>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>
            
            <form method="POST">
                <div class="form-group">
                    <label class="form-label">Database Host</label>
                    <input type="text" name="db_host" class="form-input" value="<?= htmlspecialchars($_POST['db_host'] ?? 'localhost') ?>" required>
                </div>
                
                <div class="form-group">
                    <label class="form-label">Database Name</label>
                    <input type="text" name="db_name" class="form-input" value="<?= htmlspecialchars($_POST['db_name'] ?? 'ecommerce_db') ?>" required>
                </div>
                
                <div class="form-group">
                    <label class="form-label">Database Username</label>
                    <input type="text" name="db_user" class="form-input" value="<?= htmlspecialchars($_POST['db_user'] ?? '') ?>" required>
                </div>
                
                <div class="form-group">
                    <label class="form-label">Database Password</label>
                    <input type="password" name="db_pass" class="form-input" value="<?= htmlspecialchars($_POST['db_pass'] ?? '') ?>">
                </div>
                
                <div class="form-group">
                    <label class="form-label">Application URL</label>
                    <input type="url" name="app_url" class="form-input" value="<?= htmlspecialchars($_POST['app_url'] ?? 'http://localhost/e-commerce') ?>" required>
                </div>
                
                <div class="form-group">
                    <label class="form-label">Admin Email</label>
                    <input type="email" name="admin_email" class="form-input" value="<?= htmlspecialchars($_POST['admin_email'] ?? '') ?>" required>
                </div>
                
                <div class="form-group">
                    <label class="form-label">Admin Password</label>
                    <input type="password" name="admin_password" class="form-input" required>
                </div>
                
                <button type="submit" class="btn">Install ModernShop</button>
            </form>
        <?php endif; ?>
    </div>
</body>
</html>
